<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="side_piece_size" value="0.032"/>
    <xacro:macro name="base_color">
        <color rgba="0.20 0.20 0.20 1.0"/>
    </xacro:macro>

    <xacro:macro name="layer" params="prefix parent length width height reflect">

        <link name="${prefix}_layer_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
                <xacro:base_color/>
            </visual>

            <visual name="${prefix}_top_left_piece">
                <origin xyz="${length/2-side_piece_size/2} ${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:base_color/>
            </visual>

            <visual name="${prefix}_top_right_piece">
                <origin xyz="${length/2-side_piece_size/2} -${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:base_color/>
            </visual>

            <visual name="${prefix}_mid_left_piece">
                <origin xyz="0.0 ${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size*1.8} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:base_color/>
            </visual>

            <visual name="${prefix}_mid_right_piece">
                <origin xyz="0.0 -${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size*1.8} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:base_color/>
            </visual>

            <visual name="${prefix}_bot_left_piece">
                <origin xyz="-${length/2-side_piece_size/2} ${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:base_color/>
            </visual>

            <visual name="${prefix}_bot_right_piece">
                <origin xyz="-${length/2-side_piece_size/2} -${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:base_color/>
            </visual>

        </link>

        <joint name="${parent}_to_${prefix}_layer_joint" type="fixed">
            <parent link="${parent}_link"/>
            <child link="${prefix}_layer_link"/>
            <origin xyz="0 0 ${reflect*0.065}" rpy="0 0 0"/>
        </joint>

    </xacro:macro>
    
</robot>
