<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="side_piece_size" value="0.03"/>

    <xacro:property name="motor_l" value="0.07"/>
    <xacro:property name="motor_w" value="0.022"/>
    <xacro:property name="motor_h" value="0.018"/>

    <xacro:property name="motor_offset_fb" value="0.04"/>
    <xacro:property name="motor_offset_lr" value="0.034"/>

    <xacro:property name="layer_mass" value="0.07"/>

    <xacro:macro name="base_color">
        <material name="metal">
            <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
    </xacro:macro>

    <xacro:macro name="motor_color">
        <material name="motor">
            <color rgba="${247/255} ${200/255} ${60/255} 1.0"/>
        </material>
    </xacro:macro>

    <xacro:macro name="inertial_box" params="mass x y z *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (y*y+z*z)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (x*x+z*z)}" iyz="0.0"
                    izz="${(1/12) * mass * (x*x+y*y)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="layer" params="prefix parent length width height reflect">

        <xacro:property name="layer_joint_origin">
            <origin xyz="0 0 ${reflect*0.055}" rpy="0 0 0"/>
        </xacro:property>

        <link name="${prefix}_layer_link">

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
                <xacro:base_color/>
            </visual>

            <xacro:if value="${prefix == 'upper'}"> 
                <visual name="direction_piece_1">
                    <origin xyz="${length/2-side_piece_size/2} 0.0 ${height/2}" rpy="0.0 0.0 0.0"/>
                    <geometry>
                        <box size="${side_piece_size} ${side_piece_size} ${height/2}"/>
                    </geometry>
                    <material name="header">
                        <color rgba="1.0 0.0 0.0 1.0"/>
                    </material>
                </visual>
                <visual name="direction_piece_2">
                    <origin xyz="${length/2-1.5*side_piece_size} ${width/2-side_piece_size/2} ${height/2}" rpy="0.0 0.0 0.0"/>
                    <geometry>
                        <box size="${side_piece_size} ${side_piece_size} ${height/2}"/>
                    </geometry>
                    <material name="header">
                        <color rgba="1.0 0.0 0.0 1.0"/>
                    </material>
                </visual>
                <visual name="direction_piece_3">
                    <origin xyz="${length/2-1.5*side_piece_size} -${width/2-side_piece_size/2} ${height/2}" rpy="0.0 0.0 0.0"/>
                    <geometry>
                        <box size="${side_piece_size} ${side_piece_size} ${height}"/>
                    </geometry>
                    <material name="header">
                        <color rgba="1.0 0.0 0.0 1.0"/>
                    </material>
                </visual>
            </xacro:if>

            <xacro:if value="${prefix == 'lower'}">
                <visual name="FL_motor">
                    <origin xyz="${motor_offset_fb} ${motor_offset_lr} -${motor_h/2}" rpy="0.0 0.0 0.0"/>
                    <geometry>
                        <box size="${motor_l} ${motor_w} ${motor_h}"/>
                    </geometry>
                    <xacro:motor_color/>
                </visual>
                <visual name="FR_motor">
                    <origin xyz="${motor_offset_fb} -${motor_offset_lr} -${motor_h/2}" rpy="0.0 0.0 0.0"/>
                    <geometry>
                        <box size="${motor_l} ${motor_w} ${motor_h}"/>
                    </geometry>
                    <xacro:motor_color/>
                </visual>
                <visual name="BL_motor">
                    <origin xyz="-${motor_offset_fb} ${motor_offset_lr} -${motor_h/2}" rpy="0.0 0.0 0.0"/>
                    <geometry>
                        <box size="${motor_l} ${motor_w} ${motor_h}"/>
                    </geometry>
                    <xacro:motor_color/>
                </visual>
                <visual name="BR_motor">
                    <origin xyz="-${motor_offset_fb} -${motor_offset_lr} -${motor_h/2}" rpy="0.0 0.0 0.0"/>
                    <geometry>
                        <box size="${motor_l} ${motor_w} ${motor_h}"/>
                    </geometry>
                    <xacro:motor_color/>
                </visual>
            </xacro:if>

            <visual name="${prefix}_top_left_piece">
                <origin xyz="${length/2-side_piece_size/2} ${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:base_color/>
            </visual>

            <visual name="${prefix}_top_right_piece">
                <origin xyz="${length/2-side_piece_size/2} -${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:base_color/>
            </visual>

            <visual name="${prefix}_mid_left_piece">
                <origin xyz="0.0 ${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size*1.8} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:base_color/>
            </visual>

            <visual name="${prefix}_mid_right_piece">
                <origin xyz="0.0 -${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size*1.8} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:base_color/>
            </visual>

            <visual name="${prefix}_bot_left_piece">
                <origin xyz="-${length/2-side_piece_size/2} ${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:base_color/>
            </visual>

            <visual name="${prefix}_bot_right_piece">
                <origin xyz="-${length/2-side_piece_size/2} -${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:base_color/>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width + 2*side_piece_size} ${height}"/>
                </geometry>
            </collision>
            
            <xacro:inertial_box mass="${layer_mass}" x="${length}" y="${width}" z="${height}">
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            </xacro:inertial_box>

        </link>

        <joint name="${parent}_to_${prefix}_layer_joint" type="fixed">

            <parent link="${parent}_link"/>

            <child link="${prefix}_layer_link"/>

            <xacro:insert_block name="layer_joint_origin"/>

        </joint>

    </xacro:macro>
    
</robot>
