<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="side_piece_size" value="0.03"/>

    <xacro:property name="motor_l" value="0.07"/>
    <xacro:property name="motor_w" value="0.022"/>
    <xacro:property name="motor_h" value="0.018"/>

    <xacro:property name="motor_offset_fb" value="0.04"/>
    <xacro:property name="motor_offset_lr" value="0.034"/>

    <xacro:property name="shaft_radius" value="0.0025"/>
    <xacro:property name="shaft_length" value="0.02"/>
    <xacro:property name="shaft_offset_fb" value="0.06215"/>

    <xacro:property name="base_material">
        <material name="blue">
            <color rgba="0.0 0.2 1.0 1.0"/>
        </material>
    </xacro:property>

    <xacro:property name="motor_material">
        <material name="motor_yellow">
            <color rgba="${247/255} ${200/255} ${60/255} 1.0"/>
        </material>
    </xacro:property>

    <xacro:macro name="motor_visual" params="name side_FB side_LR">
        <visual name="${name}">
            <origin xyz="${motor_offset_fb*side_FB} ${motor_offset_lr*side_LR} -${motor_h/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${motor_l} ${motor_w} ${motor_h}"/>
            </geometry>
            <xacro:insert_block name="motor_material"/>
        </visual>
        <visual name="${name}_shaft">
            <origin xyz="${shaft_offset_fb*side_FB} ${(motor_offset_lr + shaft_length)*side_LR} -${motor_h/2}" rpy="-${PI/2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${shaft_radius}" length="${shaft_length}"/>
            </geometry>
            <material name="white">
                <color rgba="1.0 1.0 1.0 1.0"/>
            </material>
        </visual>
    </xacro:macro>

    <xacro:macro name="inertial_box" params="mass x y z *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (y*y+z*z)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (x*x+z*z)}" iyz="0.0"
                    izz="${(1/12) * mass * (x*x+y*y)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="layer" params="prefix parent mass length width height reflect">

        <xacro:property name="layer_joint_origin">
            <origin xyz="0 0 ${reflect*0.055}" rpy="0 0 0"/>
        </xacro:property>

        <link name="${prefix}_layer_link">

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
                <xacro:insert_block name="base_material"/>
            </visual>

            <xacro:if value="${prefix == 'lower'}">
                <xacro:motor_visual name="FL_motor" side_FB="1" side_LR="1"/>
                <xacro:motor_visual name="FR_motor" side_FB="1" side_LR="-1"/>
                <xacro:motor_visual name="BL_motor" side_FB="-1" side_LR="1"/>
                <xacro:motor_visual name="BR_motor" side_FB="-1" side_LR="-1"/>
            </xacro:if>

            <!-- Top left piece -->
            <visual>
                <origin xyz="${length/2-side_piece_size/2} ${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:insert_block name="base_material"/>
            </visual>
            <!-- Top right piece -->
            <visual>
                <origin xyz="${length/2-side_piece_size/2} -${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:insert_block name="base_material"/>
            </visual>
            <!-- Middle left piece -->
            <visual>
                <origin xyz="0.0 ${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size*1.8} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:insert_block name="base_material"/>
            </visual>
            <!-- Middle right piece -->
            <visual>
                <origin xyz="0.0 -${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size*1.8} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:insert_block name="base_material"/>
            </visual>
            <!-- Bottom left piece -->
            <visual>
                <origin xyz="-${length/2-side_piece_size/2} ${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:insert_block name="base_material"/>
            </visual>
            <!-- Bottom right piece -->
            <visual>
                <origin xyz="-${length/2-side_piece_size/2} -${width/2+side_piece_size/2} 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size} ${side_piece_size} ${height}"/>
                </geometry>
                <xacro:insert_block name="base_material"/>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width + 2*side_piece_size} ${height}"/>
                </geometry>
            </collision>
            
            <xacro:inertial_box mass="${mass}" x="${length}" y="${width}" z="${height}">
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            </xacro:inertial_box>

        </link>

        <joint name="${parent}_to_${prefix}_layer_joint" type="fixed">

            <parent link="${parent}_link"/>

            <child link="${prefix}_layer_link"/>

            <xacro:insert_block name="layer_joint_origin"/>

        </joint>

        <gazebo reference="${prefix}_layer_link">
            <material>Gazebo/Blue</material>
        </gazebo>

        <xacro:if value="${prefix == 'upper'}"> 

        <link name="direction_piece_1">
            <visual>
                <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size} ${side_piece_size} ${height/2}"/>
                </geometry>
                <material name="header">
                    <color rgba="1.0 0.0 0.0 1.0"/>
                </material>
            </visual>
        </link>
        <joint name="direction_piece_1_joint" type="fixed">
            <origin xyz="${length/2-side_piece_size/2} 0.0 ${height/2}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}_layer_link"/>
            <child link="direction_piece_1"/>
        </joint>
        <gazebo reference="direction_piece_1">
            <material>Gazebo/Red</material>
        </gazebo>

        <link name="direction_piece_2">
            <visual>
                <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size} ${side_piece_size} ${height/2}"/>
                </geometry>
                <material name="header">
                    <color rgba="1.0 0.0 0.0 1.0"/>
                </material>
            </visual>
        </link>
        <joint name="direction_piece_2_joint" type="fixed">
            <origin xyz="${length/2-1.5*side_piece_size} ${width/2-side_piece_size/2} ${height/2}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}_layer_link"/>
            <child link="direction_piece_2"/>
        </joint>
        <gazebo reference="direction_piece_2">
            <material>Gazebo/Red</material>
        </gazebo>

        <link name="direction_piece_3">
            <visual>
                <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${side_piece_size} ${side_piece_size} ${height}"/>
                </geometry>
                <material name="header">
                    <color rgba="1.0 0.0 0.0 1.0"/>
                </material>
            </visual>
        </link>
        <joint name="direction_piece_3_joint" type="fixed">
            <origin xyz="${length/2-1.5*side_piece_size} -${width/2-side_piece_size/2} ${height/2}" rpy="0.0 0.0 0.0"/>
            <parent link="${prefix}_layer_link"/>
            <child link="direction_piece_3"/>
        </joint>
        <gazebo reference="direction_piece_3">
            <material>Gazebo/Red</material>
        </gazebo>

    </xacro:if>

    </xacro:macro>
    
</robot>
