<?xml version="1.0" encoding="UTF-8"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="pillar_offset_fb" value="0.12"/>
    <xacro:property name="pillar_offset_lr" value="0.055"/>

    <xacro:macro name="inertial_cylinder" params="mass radius length *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (3*radius*radius + length*length)}" iyz="0.0"
                    izz="${(1/2) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="pillar" params="suffix parent mass radius length side_FB side_LR">

        <xacro:property name="pillar_joint_origin">
            <origin xyz="${pillar_offset_fb*side_FB} ${pillar_offset_lr*side_LR} 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:property>

        <link name="pillar_${suffix}_link">

            <visual>
                <origin xyz="0.0 0.0 ${length/2}" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <material name="pillar_color">
                    <color rgba="${255/255} ${108/255} ${12/255} 1.0"/>
                </material>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 ${length/2}" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
            </collision>

            <xacro:inertial_cylinder mass="${mass}" radius="${radius}" length="${length}">
                <origin xyz="0.0 0.0 ${length/2}" rpy="0.0 0.0 0.0"/>
            </xacro:inertial_cylinder>

        </link>

        <joint name="${parent}_to_pillar_${suffix}_joint" type="fixed">

            <parent link="${parent}_link"/>

            <child link="pillar_${suffix}_link"/>

            <xacro:insert_block name="pillar_joint_origin"/>

        </joint>

    </xacro:macro>
    
</robot>